Repository NitBravoA92/blog-app, pull requests merged in 2023-10, with the labels that each got.

#9 feature/Integration specs for views and fix n+1 problems
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.css
  app/controllers/posts_controller.rb
  app/views/partials/_posts_comments.erb
  app/views/partials/_user.html.erb
  spec/features/comment_new_spec.rb
  spec/features/post_index_spec.rb
  spec/features/post_new_spec.rb
  spec/features/post_show_spec.rb
  spec/features/user_index_spec.rb
  spec/features/user_show_spec.rb
  spec/spec_helper.rb
Labels: documentation, enhancement, testing

#10 feature/Add Devise
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/posts_controller.rb
  app/helpers/application_helper.rb
  app/helpers/posts_helper.rb
  app/models/user.rb
  app/views/comments/new.html.erb
  app/views/devise/confirmations/new.html.erb
  app/views/devise/mailer/confirmation_instructions.html.erb
  app/views/devise/mailer/email_changed.html.erb
  app/views/devise/mailer/password_change.html.erb
  app/views/devise/mailer/reset_password_instructions.html.erb
  app/views/devise/mailer/unlock_instructions.html.erb
  app/views/devise/passwords/edit.html.erb
  app/views/devise/passwords/new.html.erb
  app/views/devise/registrations/edit.html.erb
  app/views/devise/registrations/new.html.erb
  app/views/devise/sessions/new.html.erb
  app/views/devise/shared/_error_messages.html.erb
  app/views/devise/shared/_links.html.erb
  app/views/devise/unlocks/new.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/_add_post_button.html.erb
  app/views/posts/new.html.erb
  config/environments/development.rb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20231003213738_add_devise_to_users.rb
  db/schema.rb
Labels: documentation, enhancement

#11 Add authorization rules
  Gemfile
  Gemfile.lock
  README.md
  app/assets/stylesheets/application.css
  app/controllers/application_controller.rb
  app/controllers/comments_controller.rb
  app/controllers/posts_controller.rb
  app/helpers/comments_helper.rb
  app/helpers/posts_helper.rb
  app/models/ability.rb
  app/models/post.rb
  app/models/user.rb
  app/views/devise/registrations/new.html.erb
  app/views/partials/_add_delete_comment_button.html.erb
  app/views/partials/_add_delete_post_button.erb
  app/views/partials/_comments.html.erb
  app/views/posts/show.html.erb
  config/routes.rb
  db/migrate/20231004205246_add_role_to_user.rb
  db/schema.rb
Labels: enhancement

#12 feature/Add API endpoints
  README.md
  app/controllers/api/v1/comments_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/helpers/api/comments_helper.rb
  app/views/api/comments/index.html.erb
  config/routes.rb
  spec/helpers/api/comments_helper_spec.rb
  spec/requests/api/comments_spec.rb
  spec/views/api/comments/index.html.erb_spec.rb
Labels: enhancement

#13 feature/Create API documentation
  Gemfile
  Gemfile.lock
  README.md
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/requests/api/comments_spec.rb
  spec/requests/api/posts_spec.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation, enhancement
